name = "MicroCollections"
uuid = "128add7d-3638-4c79-886c-908ea0c25c34"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.2.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
InitialValues = "22cec73e-a1b8-11e9-2c92-598750a2cf9c"

[compat]
Accessors = "0.1"
Aqua = "0.6"
BangBang = "0.4"
InitialValues = "0.2.8, 0.3"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Documenter", "Test"]
